apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yml
  - backend-configmap.yaml
  - backend-secret.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - gp3-storageclass.yaml
  - pvc.yml
